apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx # Имя объекта внутри namespace

spec:
  replicas: 2

  selector:
    matchLabels: # Имя по которому Deployment определяет свои поды
      app: nginx

  template: # Шаблон для создания контейнера
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80